config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "properties#index"

  resources :properties do
    resources :photos
  end

  resources :users do
    resources :properties
  end

  resources :photos

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :property
end

app/models/property.rb
class Property < ActiveRecord::Base
  has_many :photos
  belongs_to :user
  validates :price, :numericality => {:greater_than => 0}
  validates :title, :uniqueness => true

  def self.search(search)
    if search
      Property.where('city LIKE ?', "%#{search}%")
    else
      Property.all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :properties
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
def index
    if params[:search].present?
      @properties = Property.near(params[:search], 50, :order => :distance)
    else
      @properties = Property.all
    end
  end

  def show
    @property = Property.find(params[:id])
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(params[:property])
    if @property.save
      redirect_to @property, :notice => "Successfully created property."
    else
      render :action => 'new'
    end
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])
    if @property.update_attributes(params[:property])
      redirect_to @property, :notice  => "Successfully updated property."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @property = Property.find(params[:id])
    @property.destroy
    redirect_to properties_url, :notice => "Successfully destroyed property."
  end


private
  def property_params
    params.require(:property).permit(:title, :address, :city, :state, :country, :postal_code, :min_stay, :num_beds, :max_guests, :price, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thanks for signing up!"
      redirect_to root_url
    else
      render new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      respond_to do |format|
        format.html { redirect_to user_path(@user) }
        format.js
      end
    else
      flash[:notice] = 'Failed to Update'
      redirect_to :back
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session.clear
    flash[:notice] = "Account Deleted"
    redirect_to logout_path
  end

private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_mainnav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Peg's bnb</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="properties_path" class="active">Home</a></li>
        <li><a href="#">My Trips</a></li>
        <li><a href="#">My Properties</a></li>
        <li><a href="#">Profile</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_usernav.html.erb
<div id="user_nav" class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Peg's bnb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/usernav' %>
<%= render 'layouts/mainnav' %>
<%= flash[:notice] %>
<%= flash[:alert] %>
<%= yield %>

</body>
</html>

app/views/properties/_form.html.erb
<%= form_for @property do |f| %>

  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="form-group">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="form-group">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="form-group">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="form-group">
    <%= f.label :postal_code %><br />
    <%= f.text_field :postal_code %>
  </div>
  <div class="form-group">
    <%= f.label :min_stay %><br />
    <%= f.text_field :min_stay %>
  </div>
  <div class="form-group">
    <%= f.label :num_beds %><br />
    <%= f.text_field :num_beds %>
  </div>
 <div class="form-group">
    <%= f.label :max_guests %><br />
    <%= f.text_field :max_guests %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <p><%= f.submit "Sign Up", class: "btn btn-success"%></p>
<% end %>

app/views/properties/edit.html.erb
<h1>Edit Property</h1>

<%= render('layouts/errors', :object => @property) %>

<form action="/properties/<%= @property.id %>" method="post">

app/views/properties/index.html.erb
<h1> Properties List </h1>

<%= form_tag properties_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>

<table>
  <tr>
    <th>Title</th>
    <th>Address</th>
    <th>Bedrooms</th>
    <th>Max Guests</th>
    <th>Price</th>
  </tr>
  <% for property in @properties %>
    <tr>
      <td><%= property.title %></td>
      <td><%= property.full_address %></td>
      <td><%= property.bedrooms %></td>
      <td><%= property.max_guests %></td>
      <td><%= property.price %></td>

      <td><%= link_to "Show", property %></td>
      <td><%= link_to "Edit", edit_property_path(property) %></td>
      <td><%= link_to "Destroy", property, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New property", new_property_path %></p>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form' %>

app/views/properties/show.html.erb
<% title "Property Details" %>
<p>
  <strong>Title:</strong>
  <%= @property.title %>
</p>
<p>
  <strong>Location:</strong>
  <%= @property.city %> , <%= @property.state %> <%= @property.country %>
</p>
<p>
  <strong>Bedrooms:</strong>
  <%= @property.num_beds %>
</p>
<p>
  <strong>Maximum Guests:</strong>
  <%= @property.max_guests %>
</p>

<p>
  <strong>Minimum Stay:</strong>
  <%= @property.min_stay %>
</p>
<p>
  <strong>Price:</strong>
  <%= @property.price %>
</p>


<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@property.lat}%2C#{@property.long}" %>

<h3>Nearby Properties</h3>
<ul>
<% for property in @property.nearbys(10) %>
  <li><%= link_to property.title, property %> (<%= property.distance.round(2) %> miles)</li>
<% end %>
</ul>

<p>
  <%= link_to "Edit", edit_property_path(@property) %> |
  <%= link_to "Destroy", @property, :confirm => 'Are you sure?', :method => :delete %> |
</p>